
/*
 *	MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.yaszumod.init;

import net.minecraft.world.item.SpawnEggItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.item.BlockItem;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.Registry;

import net.mcreator.yaszumod.item.ZaniteItem;
import net.mcreator.yaszumod.item.ZaneswordItem;
import net.mcreator.yaszumod.item.YaszuitecrystalItem;
import net.mcreator.yaszumod.item.YaszuiteStaffItem;
import net.mcreator.yaszumod.item.YaszuiteGreatswordItem;
import net.mcreator.yaszumod.item.YaszuhelmetItem;
import net.mcreator.yaszumod.item.YaszuPickaxeItem;
import net.mcreator.yaszumod.item.UltaItem;
import net.mcreator.yaszumod.item.SteelarmorItem;
import net.mcreator.yaszumod.item.SteelItem;
import net.mcreator.yaszumod.item.PortalRadioItem;
import net.mcreator.yaszumod.item.LosritearmorItem;
import net.mcreator.yaszumod.item.LosoaItem;
import net.mcreator.yaszumod.item.LoseriteyesItem;
import net.mcreator.yaszumod.item.GhosteriteitemItem;
import net.mcreator.yaszumod.item.GhosteritePickaxeItem;
import net.mcreator.yaszumod.item.CottonItem;
import net.mcreator.yaszumod.item.CottonArmorItem;
import net.mcreator.yaszumod.item.CookiedoughItem;
import net.mcreator.yaszumod.item.CondomItem;
import net.mcreator.yaszumod.YaszumodMod;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;

public class YaszumodModItems {
	public static Item YASZUHELMET_HELMET;
	public static Item LOSOA;
	public static Item DUCK;
	public static Item CONDOM;
	public static Item ZANESWORD;
	public static Item GHOSTERITE;
	public static Item NERDGRASS;
	public static Item GHOSTERITEITEM;
	public static Item GOD_SPAWN_EGG;
	public static Item YASZU_PICKAXE;
	public static Item YASZUITE;
	public static Item COTTONPLANT;
	public static Item PORTAL_RADIO;
	public static Item YASZUITECRYSTAL;
	public static Item DILDO;
	public static Item YASZUITE_GREATSWORD;
	public static Item GHOSTERITE_PICKAXE;
	public static Item LOSRITE;
	public static Item MINEBOMB;
	public static Item MINEITE;
	public static Item LOSERITEYES;
	public static Item ZANITE;
	public static Item COOKIEDOUGH;
	public static Item ZANITEORE;
	public static Item ULTA;
	public static Item YASZUITE_STAFF;
	public static Item NERDSTONE;
	public static Item NERD_LEAVES;
	public static Item RUBBERLOG;
	public static Item RUBBERSAPLIN;
	public static Item COTTON;
	public static Item COTTON_ARMOR_HELMET;
	public static Item COTTON_ARMOR_CHESTPLATE;
	public static Item COTTON_ARMOR_LEGGINGS;
	public static Item COTTON_ARMOR_BOOTS;
	public static Item STEEL;
	public static Item LOSRITEARMOR_HELMET;
	public static Item LOSRITEARMOR_CHESTPLATE;
	public static Item LOSRITEARMOR_LEGGINGS;
	public static Item LOSRITEARMOR_BOOTS;
	public static Item STEELARMOR_HELMET;
	public static Item STEELARMOR_CHESTPLATE;
	public static Item STEELARMOR_LEGGINGS;
	public static Item STEELARMOR_BOOTS;

	public static void load() {
		YASZUHELMET_HELMET = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "yaszuhelmet_helmet"), new YaszuhelmetItem.Helmet());
		LOSOA = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "losoa"), new LosoaItem());
		DUCK = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "duck"), new BlockItem(YaszumodModBlocks.DUCK, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(YaszumodModTabs.TAB_YASZUSMOD).register(content -> content.accept(DUCK));
		CONDOM = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "condom"), new CondomItem());
		ZANESWORD = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "zanesword"), new ZaneswordItem());
		GHOSTERITE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "ghosterite"), new BlockItem(YaszumodModBlocks.GHOSTERITE, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(YaszumodModTabs.TAB_YASZUSMOD).register(content -> content.accept(GHOSTERITE));
		NERDGRASS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "nerdgrass"), new BlockItem(YaszumodModBlocks.NERDGRASS, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(YaszumodModTabs.TAB_YASZUSMOD).register(content -> content.accept(NERDGRASS));
		GHOSTERITEITEM = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "ghosteriteitem"), new GhosteriteitemItem());
		GOD_SPAWN_EGG = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "god_spawn_egg"), new SpawnEggItem(YaszumodModEntities.GOD, -65536, -1, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(YaszumodModTabs.TAB_YASZUSMOD).register(content -> content.accept(GOD_SPAWN_EGG));
		YASZU_PICKAXE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "yaszu_pickaxe"), new YaszuPickaxeItem());
		YASZUITE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "yaszuite"), new BlockItem(YaszumodModBlocks.YASZUITE, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(YaszumodModTabs.TAB_YASZUSMOD).register(content -> content.accept(YASZUITE));
		COTTONPLANT = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "cottonplant"), new BlockItem(YaszumodModBlocks.COTTONPLANT, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeModeTabs.NATURAL_BLOCKS).register(content -> content.accept(COTTONPLANT));
		PORTAL_RADIO = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "portal_radio"), new PortalRadioItem());
		YASZUITECRYSTAL = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "yaszuitecrystal"), new YaszuitecrystalItem());
		DILDO = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "dildo"), new BlockItem(YaszumodModBlocks.DILDO, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(YaszumodModTabs.TAB_YASZUSMOD).register(content -> content.accept(DILDO));
		YASZUITE_GREATSWORD = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "yaszuite_greatsword"), new YaszuiteGreatswordItem());
		GHOSTERITE_PICKAXE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "ghosterite_pickaxe"), new GhosteritePickaxeItem());
		LOSRITE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "losrite"), new BlockItem(YaszumodModBlocks.LOSRITE, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(YaszumodModTabs.TAB_YASZUSMOD).register(content -> content.accept(LOSRITE));
		MINEBOMB = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "minebomb"), new BlockItem(YaszumodModBlocks.MINEBOMB, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(YaszumodModTabs.TAB_YASZUSMOD).register(content -> content.accept(MINEBOMB));
		MINEITE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "mineite"), new BlockItem(YaszumodModBlocks.MINEITE, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(YaszumodModTabs.TAB_YASZUSMOD).register(content -> content.accept(MINEITE));
		LOSERITEYES = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "loseriteyes"), new LoseriteyesItem());
		ZANITE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "zanite"), new ZaniteItem());
		COOKIEDOUGH = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "cookiedough"), new CookiedoughItem());
		ZANITEORE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "zaniteore"), new BlockItem(YaszumodModBlocks.ZANITEORE, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(YaszumodModTabs.TAB_YASZUSMOD).register(content -> content.accept(ZANITEORE));
		ULTA = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "ulta"), new UltaItem());
		YASZUITE_STAFF = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "yaszuite_staff"), new YaszuiteStaffItem());
		NERDSTONE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "nerdstone"), new BlockItem(YaszumodModBlocks.NERDSTONE, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(YaszumodModTabs.TAB_YASZUSMOD).register(content -> content.accept(NERDSTONE));
		NERD_LEAVES = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "nerd_leaves"), new BlockItem(YaszumodModBlocks.NERD_LEAVES, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(YaszumodModTabs.TAB_YASZUSMOD).register(content -> content.accept(NERD_LEAVES));
		RUBBERLOG = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "rubberlog"), new BlockItem(YaszumodModBlocks.RUBBERLOG, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(YaszumodModTabs.TAB_YASZUSMOD).register(content -> content.accept(RUBBERLOG));
		RUBBERSAPLIN = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "rubbersaplin"), new BlockItem(YaszumodModBlocks.RUBBERSAPLIN, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeModeTabs.NATURAL_BLOCKS).register(content -> content.accept(RUBBERSAPLIN));
		COTTON = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "cotton"), new CottonItem());
		COTTON_ARMOR_HELMET = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "cotton_armor_helmet"), new CottonArmorItem.Helmet());
		COTTON_ARMOR_CHESTPLATE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "cotton_armor_chestplate"), new CottonArmorItem.Chestplate());
		COTTON_ARMOR_LEGGINGS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "cotton_armor_leggings"), new CottonArmorItem.Leggings());
		COTTON_ARMOR_BOOTS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "cotton_armor_boots"), new CottonArmorItem.Boots());
		STEEL = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "steel"), new SteelItem());
		LOSRITEARMOR_HELMET = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "losritearmor_helmet"), new LosritearmorItem.Helmet());
		LOSRITEARMOR_CHESTPLATE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "losritearmor_chestplate"), new LosritearmorItem.Chestplate());
		LOSRITEARMOR_LEGGINGS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "losritearmor_leggings"), new LosritearmorItem.Leggings());
		LOSRITEARMOR_BOOTS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "losritearmor_boots"), new LosritearmorItem.Boots());
		STEELARMOR_HELMET = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "steelarmor_helmet"), new SteelarmorItem.Helmet());
		STEELARMOR_CHESTPLATE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "steelarmor_chestplate"), new SteelarmorItem.Chestplate());
		STEELARMOR_LEGGINGS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "steelarmor_leggings"), new SteelarmorItem.Leggings());
		STEELARMOR_BOOTS = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(YaszumodMod.MODID, "steelarmor_boots"), new SteelarmorItem.Boots());
	}
}
